#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 30 18:10:16 CST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=TrueLightFX v5.1.1.zip
